name: Bkbc_Twd2Btc
description: A sample Polymer application
dependencies:
  crypto: any
  intl: any
  polymer: any
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/bkbc_twd2btc.html
